import type { TeacherSetting } from '../types/teacher/teacher.type';

export const TEACHERS_SETTINGS_DATA: TeacherSetting[] = [
    {
        name: '강기원',
        chalk: { type: 'academy', detail: '학원분필 사용 (흰4, 노4, 빨2, 파2 세팅)' },
        eraser: '5개, 쉬는시간 3분간 사용하던 지우개로만 정리(물x)',
        mic: 'personal',
        ppt: false,
        detail: '좌측 topic/개념설명 제외, 우측 문제들만 지우기',
        email: false,
    },
    {
        name: '강수영',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '강승연',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: true,
        detail: '칠판 조명 끄기 / 강의 시작 전 파우치 받아서 분필 세팅 및 종료 후 개인물품 정리하여 6층 강사대기실 강승연T에게 전달/ 강의 종료 후 영상 메일 전송 필수',
        email: true,
    },
    {
        name: '강준호',
        chalk: { type: 'mixed', detail: '분필 1세트 : 학원흰색2+개인컬러분필(빨노파)(6층교재실)' },
        eraser: '[분필 - 지우개 - 분필 - 지우개 - 분필 - 분필 - 지우개] 세팅 + 젖은 물 지우개 6개 교탁 옆에 세팅',
        mic: 'academy',
        ppt: false,
        detail: '[지-분-지-분-지-분-분-지] 순서 세팅',
        email: false,
    },
    {
        name: '강지연',
        chalk: { type: 'academy', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '강영종',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '강철중',
        chalk: { type: 'mixed', detail: '개인분필은 직접 세팅하심' },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '개인분필은 직접 세팅하심',
        email: false,
    },
    {
        name: '고아름',
        chalk: { type: 'mixed', detail: '칠판 가운데는 비우고 양 옆에 학원분필 각 1세트씩(총 2세트) 세팅' },
        eraser: 'default',
        mic: 'academy',
        ppt: true,
        detail: '단상은 피피티 피해서 교단위로 올려주세요',
        email: false,
    },
    {
        name: '김강민',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '김기대',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '김기병',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '포인터 세팅',
        email: false,
    },
    {
        name: '김기원',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '김미향',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: true,
        detail: '개인노트북+ppt = 직원세팅',
        email: false,
    },
    {
        name: '김범찬',
        chalk: { type: 'personal', detail: '학원 분필도 일단 세팅' },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '시험 30분',
        email: false,
    },
    {
        name: '김성도',
        chalk: { type: 'academy', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '김연호',
        chalk: { type: 'academy', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '김윤환',
        chalk: { type: 'academy', detail: undefined },
        eraser: '쉬는시간에 패브릭으로 지워주세요',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '김종진',
        chalk: { type: 'academy', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: true,
        detail: '빔프로젝터 켜기',
        email: false,
    },
    {
        name: '김재홍',
        chalk: {
            type: 'academy',
            detail: '학원분필 비어보이지않도록 많이 깔기, [ 지우개 + 흰2빨노파 + 흰분필2개 ] 로 5세트 학원 흰 분필 두 통 교탁위에 두기 ',
        },
        eraser: '5세트 [지우개 + 흰2빨노파 + 흰분필2개]',
        mic: 'personal',
        ppt: false,
        detail: '흰 분필 두 통 교탁 위에 두기, 비어보이지 않게 많이 깔기',
        email: false,
    },
    {
        name: '김재훈',
        chalk: { type: 'academy', detail: undefined },
        eraser: '스크린 기준 가운데 2개 + 스크린 벗어나서 2개',
        mic: 'academy',
        ppt: false,
        detail: '마이크 볼륨 작게(2/3까지)',
        email: false,
    },
    {
        name: '김지혁',
        chalk: { type: 'academy', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: true,
        detail: '',
        email: false,
    },
    {
        name: '김태훈',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '권구승',
        chalk: { type: 'personal', detail: '강사님이 직접 세팅하심' },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '강사님이 직접 세팅하심',
        email: false,
    },
    {
        name: '나진환',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: true,
        detail: '',
        email: false,
    },
    {
        name: '남지현',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '류동원',
        chalk: { type: 'personal', detail: '왼쪽 위 시간 적혀 있으면 지우지 말 것' },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '왼쪽 위 시간 적혀 있으면 지우지 말 것',
        email: false,
    },
    {
        name: '문서연',
        chalk: { type: 'personal', detail: undefined },
        eraser: '지우개패드 개인용 사용하심 (강의 전 개인용 붙여서 세팅하기), 여분 지우개 패드 5개, 옆책상에 꺼내두기 + 강의끝나고 강사님 가실때 개인용 지우개패드 가방에 넣어드리기 (쉬는시간, 수업끝나고 지우는건 우리껄로) ',
        mic: 'personal',
        ppt: true,
        detail: '수업 후 개인 패드 가방에 넣어드리기',
        email: false,
    },
    {
        name: '박근수',
        chalk: { type: 'academy', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '박준호',
        chalk: { type: 'personal', detail: undefined },
        eraser: '4개 (조금 멀리 세팅)',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '박지윤',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '포인터 세팅',
        email: false,
    },
    {
        name: '변춘수',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '배경민',
        chalk: { type: 'personal', detail: undefined },
        eraser: '지우개 옆 학원 노란색 1개 세팅',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '서준혁',
        chalk: { type: 'personal', detail: '강사님 오시면 분필 받아서 세팅' },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '강사님 오시면 분필 받아서 세팅',
        email: false,
    },
    {
        name: '서지현',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '성치경',
        chalk: { type: 'mixed', detail: '학원 분필은 노란색만 세팅' },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '학원 분필은 노란색만 세팅',
        email: false,
    },
    {
        name: '송준혁',
        chalk: {
            type: 'mixed',
            detail: '분필세팅 : 흰4(학원)+ 개인분필(6층강대실) 색깔별로 1개씩 + 혼자 와서 연습하시니까 안 하면 세팅(9:50까지) + 개인분필통은 세팅 후 교탁 옆에 통째로 두기',
        },
        eraser: '스크린 화면 반 기준 좌측에만 4개',
        mic: 'academy',
        ppt: false,
        detail: '9:50까지 세팅 완료, 개인분필통은 교탁 옆에 두기',
        email: false,
    },
    {
        name: '심규원',
        chalk: { type: 'academy', detail: undefined },
        eraser: '물지우개 2개 세팅',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '심용선',
        chalk: { type: 'academy', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '마이크 볼륨 절반으로 줄이기',
        email: false,
    },
    {
        name: '심찬우',
        chalk: { type: 'mixed', detail: '배치표 준수, 쉬는시간 없음, 영상 자료 촬영 시 조그 조정' },
        eraser: '지우개 5개 + 문학 수업 시 마른 지우개 여분 5개씩 2세트',
        mic: 'personal',
        ppt: true,
        detail: '배치표 준수, 쉬는시간 없음, 영상 자료 촬영 시 조그 조정',
        email: false,
    },
    {
        name: '안가람',
        chalk: { type: 'academy', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '엄영대',
        chalk: { type: 'mixed', detail: '포인터 세팅, 문항분석표 뽑기' },
        eraser: '쉬는시간 패브릭 지우개로 정리',
        mic: 'academy',
        ppt: true,
        detail: '포인터 세팅, 문항분석표 뽑기',
        email: false,
    },
    {
        name: '엄소연',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '오택민',
        chalk: { type: 'personal', detail: '남은 분필 상태에 따른 처리 규정 확인' },
        eraser: '쉬는시간에 패브릭 지우개로 지우기',
        mic: 'academy',
        ppt: false,
        detail: '남은 분필 상태에 따른 처리 규정 확인',
        email: false,
    },
    {
        name: '유성호',
        chalk: { type: 'academy', detail: '학원분필 5개 세팅' },
        eraser: '지우개 + 물지우개 2개 (교탁 옆)',
        mic: 'academy',
        ppt: false,
        detail: '학원분필 5개 세팅',
        email: false,
    },
    {
        name: '유신',
        chalk: { type: 'personal', detail: '포인터 세팅, 조그 터치 절대 금지' },
        eraser: '스크린 안에 5개',
        mic: 'academy',
        ppt: false,
        detail: '포인터 세팅, 조그 터치 절대 금지',
        email: false,
    },
    {
        name: '유주오',
        chalk: { type: 'academy', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '윤준수',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '윤지환',
        chalk: { type: 'mixed', detail: '조그 판서 위주(인물 우측 고정) 촬영' },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '조그 판서 위주(인물 우측 고정) 촬영',
        email: false,
    },
    {
        name: '이승헌',
        chalk: { type: 'academy', detail: '같이 오시는 실장님이 세팅하심' },
        eraser: '연강 시 쉬는시간에 지우기',
        mic: 'academy',
        ppt: false,
        detail: '같이 오시는 실장님이 세팅하심',
        email: false,
    },
    {
        name: '이신혁',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '마이크 소리 조금 줄이기',
        email: false,
    },
    {
        name: '이윤희',
        chalk: { type: 'academy', detail: undefined },
        eraser: '스크린 범위에 가깝게 세팅',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '이종걸',
        chalk: { type: 'mixed', detail: '학원 분필은 흰색만 2개씩' },
        eraser: '쉬는시간에 마른 지우개로 지우기',
        mic: 'academy',
        ppt: false,
        detail: '학원 분필은 흰색만 2개씩',
        email: false,
    },
    {
        name: '이종길',
        chalk: { type: 'academy', detail: '본인이 필요하면 직접 더 꺼내 쓰심' },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '본인이 필요하면 직접 더 꺼내 쓰심',
        email: false,
    },
    {
        name: '이준호',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: true,
        detail: '',
        email: false,
    },
    {
        name: '장의순',
        chalk: { type: 'academy', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '시험 20분',
        email: false,
    },
    {
        name: '장재원',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '조그 집중 촬영',
        email: false,
    },
    {
        name: '정승준',
        chalk: { type: 'personal', detail: '종이컵 속 분필 우선 사용' },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '종이컵 속 분필 우선 사용',
        email: false,
    },
    {
        name: '정재영',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '정재일',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '정태혁',
        chalk: { type: 'mixed', detail: '(개인 분필은 강사 대기실) 학원 분필은 흰색만 2개씩 세팅' },
        eraser: '지우개-분필 4세트 모두 피피티 안쪽으로 들어오도록 세팅',
        mic: 'academy',
        ppt: true,
        email: false,
    },
    {
        name: '전현정',
        chalk: { type: 'personal', detail: undefined },
        eraser: '쉬는시간 칠판 정리 x',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '조영상',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '조은정',
        chalk: { type: 'personal', detail: '분필 8개(보라 제외), 색별 하나는 케이스 장착' },
        eraser: '패브릭 여분 5개 교탁 옆 세팅',
        mic: 'academy',
        ppt: false,
        detail: '분필 8개(보라 제외), 색별 하나는 케이스 장착',
        email: false,
    },
    {
        name: '차주현',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '최원준',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '최은석',
        chalk: { type: 'mixed', detail: '포인터 교탁 위 세팅' },
        eraser: 'ppt 주변으로 4개',
        mic: 'academy',
        ppt: true,
        detail: '포인터 교탁 위 세팅',
        email: false,
    },
    {
        name: '최정은',
        chalk: { type: 'personal', detail: '마이크 확인 필요' },
        eraser: '칠판 중앙부터 우측으로 4개',
        mic: 'academy',
        ppt: true,
        detail: '마이크 확인 필요',
        email: false,
    },
    {
        name: '최지욱',
        chalk: { type: 'personal', detail: '에어컨 18도 최대바람, 왼쪽 공지사항 확인' },
        eraser: '지우개 6개 + 패브릭 6개 여분',
        mic: 'personal',
        ppt: false,
        detail: '에어컨 18도 최대바람, 왼쪽 공지사항 확인',
        email: false,
    },
    {
        name: '탁윤석',
        chalk: { type: 'mixed', detail: '본인 직접 세팅' },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '본인 직접 세팅',
        email: false,
    },
    {
        name: '한세빈',
        chalk: { type: 'personal', detail: '포인터 세팅, 강의영상+시험분석 메일 전송' },
        eraser: '지우개 ppt 근처로 세팅',
        mic: 'academy',
        ppt: true,
        detail: '포인터 세팅, 강의영상+시험분석 메일 전송',
        email: true,
    },
    {
        name: '한혜선',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '현유찬',
        chalk: { type: 'personal', detail: '6층 강사대기실에서 쓰시기 좋게만 꺼내놓기' },
        eraser: 'default',
        mic: 'personal',
        ppt: false,
        email: false,
    },
    {
        name: '현정훈',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: false,
        detail: '',
        email: false,
    },
    {
        name: '황석진',
        chalk: { type: 'personal', detail: undefined },
        eraser: 'default',
        mic: 'academy',
        ppt: true,
        detail: '',
        email: false,
    },
    {
        name: '황용일',
        chalk: { type: 'personal', detail: '직접 세팅' },
        eraser: 'default',
        mic: 'academy',
        ppt: true,
        detail: '직접 세팅',
        email: false,
    },
];
