/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RandomRouteImport } from './routes/random'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingIndexRouteImport } from './routes/setting/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsPreFirstPeriodTasksRouteImport } from './routes/docs/pre-first-period-tasks'
import { Route as LoginOauth2CodeKakaoRouteImport } from './routes/login.oauth2.code.kakao'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingIndexRoute = SettingIndexRouteImport.update({
  id: '/setting/',
  path: '/setting/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPreFirstPeriodTasksRoute = DocsPreFirstPeriodTasksRouteImport.update({
  id: '/docs/pre-first-period-tasks',
  path: '/docs/pre-first-period-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOauth2CodeKakaoRoute = LoginOauth2CodeKakaoRouteImport.update({
  id: '/login/oauth2/code/kakao',
  path: '/login/oauth2/code/kakao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/random': typeof RandomRoute
  '/schedule': typeof ScheduleRoute
  '/docs/pre-first-period-tasks': typeof DocsPreFirstPeriodTasksRoute
  '/docs/': typeof DocsIndexRoute
  '/setting/': typeof SettingIndexRoute
  '/login/oauth2/code/kakao': typeof LoginOauth2CodeKakaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/random': typeof RandomRoute
  '/schedule': typeof ScheduleRoute
  '/docs/pre-first-period-tasks': typeof DocsPreFirstPeriodTasksRoute
  '/docs': typeof DocsIndexRoute
  '/setting': typeof SettingIndexRoute
  '/login/oauth2/code/kakao': typeof LoginOauth2CodeKakaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/random': typeof RandomRoute
  '/schedule': typeof ScheduleRoute
  '/docs/pre-first-period-tasks': typeof DocsPreFirstPeriodTasksRoute
  '/docs/': typeof DocsIndexRoute
  '/setting/': typeof SettingIndexRoute
  '/login/oauth2/code/kakao': typeof LoginOauth2CodeKakaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/random'
    | '/schedule'
    | '/docs/pre-first-period-tasks'
    | '/docs/'
    | '/setting/'
    | '/login/oauth2/code/kakao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/random'
    | '/schedule'
    | '/docs/pre-first-period-tasks'
    | '/docs'
    | '/setting'
    | '/login/oauth2/code/kakao'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/random'
    | '/schedule'
    | '/docs/pre-first-period-tasks'
    | '/docs/'
    | '/setting/'
    | '/login/oauth2/code/kakao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  RandomRoute: typeof RandomRoute
  ScheduleRoute: typeof ScheduleRoute
  DocsPreFirstPeriodTasksRoute: typeof DocsPreFirstPeriodTasksRoute
  DocsIndexRoute: typeof DocsIndexRoute
  SettingIndexRoute: typeof SettingIndexRoute
  LoginOauth2CodeKakaoRoute: typeof LoginOauth2CodeKakaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting/': {
      id: '/setting/'
      path: '/setting'
      fullPath: '/setting/'
      preLoaderRoute: typeof SettingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/pre-first-period-tasks': {
      id: '/docs/pre-first-period-tasks'
      path: '/docs/pre-first-period-tasks'
      fullPath: '/docs/pre-first-period-tasks'
      preLoaderRoute: typeof DocsPreFirstPeriodTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/oauth2/code/kakao': {
      id: '/login/oauth2/code/kakao'
      path: '/login/oauth2/code/kakao'
      fullPath: '/login/oauth2/code/kakao'
      preLoaderRoute: typeof LoginOauth2CodeKakaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  RandomRoute: RandomRoute,
  ScheduleRoute: ScheduleRoute,
  DocsPreFirstPeriodTasksRoute: DocsPreFirstPeriodTasksRoute,
  DocsIndexRoute: DocsIndexRoute,
  SettingIndexRoute: SettingIndexRoute,
  LoginOauth2CodeKakaoRoute: LoginOauth2CodeKakaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
